"""Rename remarks column to root_cause in Incident model

Revision ID: fec7f69ce0b1
Revises: 3a3d288008de
Create Date: 2025-04-15 03:33:27.596211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec7f69ce0b1'
down_revision = '3a3d288008de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_cause', sa.Text(), nullable=True))
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), nullable=True))
        batch_op.drop_column('root_cause')

    # ### end Alembic commands ###
